/* 获取城市列表 */
export async function fetchCityData() {
  return [
    {
      citys: [
        { cityName: '北京市' },
        { cityName: '天津市' },
        { cityName: '上海市' },
        { cityName: '重庆市' },
        { cityName: '香港特别行政区' },
        { cityName: '澳门特别行政区' },
      ],
      provinceName: '直辖市/特别行政区',
    },
    {
      provinceName: '海外地区',
      citys: [
        { cityName: '阿富汗' },
        { cityName: '奥兰群岛' },
        { cityName: '阿尔巴尼亚' },
        { cityName: '阿尔及利亚' },
        { cityName: '美属萨摩亚' },
        { cityName: '安道尔' },
        { cityName: '安哥拉' },
        { cityName: '安圭拉' },
        { cityName: '南极洲' },
        { cityName: '安提瓜和巴布达' },
        { cityName: '阿根廷' },
        { cityName: '亚美尼亚' },
        { cityName: '阿鲁巴' },
        { cityName: '澳大利亚' },
        { cityName: '奥地利' },
        { cityName: '阿塞拜疆' },
        { cityName: '巴哈马' },
        { cityName: '巴林' },
        { cityName: '孟加拉国' },
        { cityName: '巴巴多斯' },
        { cityName: '白俄罗斯' },
        { cityName: '比利时' },
        { cityName: '伯利兹' },
        { cityName: '贝宁' },
        { cityName: '百慕大' },
        { cityName: '不丹' },
        { cityName: '玻利维亚' },
        { cityName: '波黑' },
        { cityName: '博茨瓦纳' },
        { cityName: '布维岛' },
        { cityName: '巴西' },
        { cityName: '英属印度洋领地' },
        { cityName: '文莱' },
        { cityName: '保加利亚' },
        { cityName: '布基纳法索' },
        { cityName: '布隆迪' },
        { cityName: '柬埔寨' },
        { cityName: '喀麦隆' },
        { cityName: '加拿大' },
        { cityName: '佛得角' },
        { cityName: '开曼群岛' },
        { cityName: '中非' },
        { cityName: '乍得' },
        { cityName: '智利' },
        { cityName: '圣诞岛' },
        { cityName: '科科斯（基林）群岛' },
        { cityName: '哥伦比亚' },
        { cityName: '科摩罗' },
        { cityName: '刚果（布）' },
        { cityName: '刚果（金）' },
        { cityName: '库克群岛' },
        { cityName: '哥斯达黎加' },
        { cityName: '科特迪瓦' },
        { cityName: '克罗地亚' },
        { cityName: '古巴' },
        { cityName: '塞浦路斯' },
        { cityName: '捷克' },
        { cityName: '丹麦' },
        { cityName: '吉布提' },
        { cityName: '多米尼克' },
        { cityName: '多米尼加' },
        { cityName: '厄瓜多尔' },
        { cityName: '埃及' },
        { cityName: '萨尔瓦多' },
        { cityName: '赤道几内亚' },
        { cityName: '厄立特里亚' },
        { cityName: '爱沙尼亚' },
        { cityName: '埃塞俄比亚' },
        { cityName: '福克兰群岛（马尔维纳斯）' },
        { cityName: '法罗群岛' },
        { cityName: '斐济' },
        { cityName: '芬兰' },
        { cityName: '法国' },
        { cityName: '法属圭亚那' },
        { cityName: '法属波利尼西亚' },
        { cityName: '法属南部领地' },
        { cityName: '加蓬' },
        { cityName: '冈比亚' },
        { cityName: '格鲁吉亚' },
        { cityName: '德国' },
        { cityName: '加纳' },
        { cityName: '直布罗陀' },
        { cityName: '希腊' },
        { cityName: '格陵兰' },
        { cityName: '格林纳达' },
        { cityName: '瓜德罗普' },
        { cityName: '关岛' },
        { cityName: '危地马拉' },
        { cityName: '格恩西岛' },
        { cityName: '几内亚' },
        { cityName: '几内亚比绍' },
        { cityName: '圭亚那' },
        { cityName: '海地' },
        { cityName: '赫德岛和麦克唐纳岛' },
        { cityName: '梵蒂冈' },
        { cityName: '洪都拉斯' },
        { cityName: '匈牙利' },
        { cityName: '冰岛' },
        { cityName: '印度' },
        { cityName: '印度尼西亚' },
        { cityName: '伊朗' },
        { cityName: '伊拉克' },
        { cityName: '爱尔兰' },
        { cityName: '英国属地曼岛' },
        { cityName: '以色列' },
        { cityName: '意大利' },
        { cityName: '牙买加' },
        { cityName: '日本' },
        { cityName: '泽西岛' },
        { cityName: '约旦' },
        { cityName: '哈萨克斯坦' },
        { cityName: '肯尼亚' },
        { cityName: '基里巴斯' },
        { cityName: '朝鲜' },
        { cityName: '韩国' },
        { cityName: '科威特' },
        { cityName: '吉尔吉斯斯坦' },
        { cityName: '老挝' },
        { cityName: '拉脱维亚' },
        { cityName: '黎巴嫩' },
        { cityName: '莱索托' },
        { cityName: '利比里亚' },
        { cityName: '利比亚' },
        { cityName: '列支敦士登' },
        { cityName: '立陶宛' },
        { cityName: '卢森堡' },
        { cityName: '前南马其顿' },
        { cityName: '马达加斯加' },
        { cityName: '马拉维' },
        { cityName: '马来西亚' },
        { cityName: '马尔代夫' },
        { cityName: '马里' },
        { cityName: '马耳他' },
        { cityName: '马绍尔群岛' },
        { cityName: '马提尼克' },
        { cityName: '毛利塔尼亚' },
        { cityName: '毛里求斯' },
        { cityName: '马约特' },
        { cityName: '墨西哥' },
        { cityName: '密克罗尼西亚联邦' },
        { cityName: '摩尔多瓦' },
        { cityName: '摩纳哥' },
        { cityName: '蒙古' },
        { cityName: '黑山' },
        { cityName: '蒙特塞拉特' },
        { cityName: '摩洛哥' },
        { cityName: '莫桑比克' },
        { cityName: '缅甸' },
        { cityName: '纳米比亚' },
        { cityName: '瑙鲁' },
        { cityName: '尼泊尔' },
        { cityName: '荷兰' },
        { cityName: '荷属安的列斯' },
        { cityName: '新喀里多尼亚' },
        { cityName: '新西兰' },
        { cityName: '尼加拉瓜' },
        { cityName: '尼日尔' },
        { cityName: '尼日利亚' },
        { cityName: '纽埃' },
        { cityName: '诺福克岛' },
        { cityName: '北马里亚纳' },
        { cityName: '挪威' },
        { cityName: '阿曼' },
        { cityName: '巴基斯坦' },
        { cityName: '帕劳' },
        { cityName: '巴勒斯坦' },
        { cityName: '巴拿马' },
        { cityName: '巴布亚新几内亚' },
        { cityName: '巴拉圭' },
        { cityName: '秘鲁' },
        { cityName: '菲律宾' },
        { cityName: '皮特凯恩' },
        { cityName: '波兰' },
        { cityName: '葡萄牙' },
        { cityName: '波多黎各' },
        { cityName: '卡塔尔' },
        { cityName: '留尼汪' },
        { cityName: '罗马尼亚' },
        { cityName: '俄罗斯联邦' },
        { cityName: '卢旺达' },
        { cityName: '圣赫勒拿' },
        { cityName: '圣基茨和尼维斯' },
        { cityName: '圣卢西亚' },
        { cityName: '圣皮埃尔和密克隆' },
        { cityName: '圣文森特和格林纳丁斯' },
        { cityName: '萨摩亚' },
        { cityName: '圣马力诺' },
        { cityName: '圣多美和普林西比' },
        { cityName: '沙特阿拉伯' },
        { cityName: '塞内加尔' },
        { cityName: '塞尔维亚' },
        { cityName: '塞舌尔' },
        { cityName: '塞拉利昂' },
        { cityName: '新加坡' },
        { cityName: '斯洛伐克' },
        { cityName: '斯洛文尼亚' },
        { cityName: '所罗门群岛' },
        { cityName: '索马里' },
        { cityName: '南非' },
        { cityName: '南乔治亚岛和南桑德韦奇岛' },
        { cityName: '西班牙' },
        { cityName: '斯里兰卡' },
        { cityName: '苏丹' },
        { cityName: '苏里南' },
        { cityName: '斯瓦尔巴岛和扬马延岛' },
        { cityName: '斯威士兰' },
        { cityName: '瑞典' },
        { cityName: '瑞士' },
        { cityName: '叙利亚' },
        { cityName: '塔吉克斯坦' },
        { cityName: '坦桑尼亚' },
        { cityName: '泰国' },
        { cityName: '东帝汶' },
        { cityName: '多哥' },
        { cityName: '托克劳' },
        { cityName: '汤加' },
        { cityName: '特立尼达和多巴哥' },
        { cityName: '突尼斯' },
        { cityName: '土耳其' },
        { cityName: '土库曼斯坦' },
        { cityName: '特克斯和凯科斯群岛' },
        { cityName: '图瓦卢' },
        { cityName: '乌干达' },
        { cityName: '乌克兰' },
        { cityName: '阿联酋' },
        { cityName: '英国' },
        { cityName: '美国' },
        { cityName: '美国本土外小岛屿' },
        { cityName: '乌拉圭' },
        { cityName: '乌兹别克斯坦' },
        { cityName: '瓦努阿图' },
        { cityName: '委内瑞拉' },
        { cityName: '越南' },
        { cityName: '英属维尔京群岛' },
        { cityName: '美属维尔京群岛' },
        { cityName: '瓦利斯和富图纳' },
        { cityName: '西撒哈拉' },
        { cityName: '也门' },
        { cityName: '赞比亚' },
        { cityName: '津巴布韦' },
      ],
    },
    {
      provinceName: '河北省',
      citys: [
        { cityName: '石家庄市' },
        { cityName: '唐山市' },
        { cityName: '秦皇岛市' },
        { cityName: '邯郸市' },
        { cityName: '邢台市' },
        { cityName: '保定市' },
        { cityName: '张家口市' },
        { cityName: '承德市' },
        { cityName: '沧州市' },
        { cityName: '廊坊市' },
        { cityName: '衡水市' },
      ],
    },
    {
      provinceName: '山西省',
      citys: [
        { cityName: '太原市' },
        { cityName: '大同市' },
        { cityName: '阳泉市' },
        { cityName: '长治市' },
        { cityName: '晋城市' },
        { cityName: '朔州市' },
        { cityName: '晋中市' },
        { cityName: '运城市' },
        { cityName: '忻州市' },
        { cityName: '临汾市' },
        { cityName: '吕梁市' },
      ],
    },
    {
      provinceName: '广东省',
      citys: [
        { cityName: '广州市' },
        { cityName: '韶关市' },
        { cityName: '深圳市' },
        { cityName: '珠海市' },
        { cityName: '汕头市' },
        { cityName: '佛山市' },
        { cityName: '江门市' },
        { cityName: '湛江市' },
        { cityName: '茂名市' },
        { cityName: '肇庆市' },
        { cityName: '惠州市' },
        { cityName: '梅州市' },
        { cityName: '汕尾市' },
        { cityName: '河源市' },
        { cityName: '阳江市' },
        { cityName: '清远市' },
        { cityName: '东莞市' },
        { cityName: '中山市' },
        { cityName: '潮州市' },
        { cityName: '揭阳市' },
        { cityName: '云浮市' },
      ],
    },
    {
      provinceName: '内蒙古自治区',
      citys: [
        { cityName: '呼和浩特市' },
        { cityName: '包头市' },
        { cityName: '乌海市' },
        { cityName: '赤峰市' },
        { cityName: '通辽市' },
        { cityName: '鄂尔多斯市' },
        { cityName: '呼伦贝尔市' },
        { cityName: '巴彦淖尔市' },
        { cityName: '乌兰察布市' },
        { cityName: '兴安盟' },
        { cityName: '锡林郭勒盟' },
        { cityName: '阿拉善盟' },
      ],
    },
    {
      provinceName: '辽宁省',
      citys: [
        { cityName: '沈阳市' },
        { cityName: '大连市' },
        { cityName: '鞍山市' },
        { cityName: '抚顺市' },
        { cityName: '本溪市' },
        { cityName: '丹东市' },
        { cityName: '锦州市' },
        { cityName: '营口市' },
        { cityName: '阜新市' },
        { cityName: '辽阳市' },
        { cityName: '盘锦市' },
        { cityName: '铁岭市' },
        { cityName: '朝阳市' },
        { cityName: '葫芦岛市' },
      ],
    },
    {
      provinceName: '吉林省',
      citys: [
        { cityName: '长春市' },
        { cityName: '吉林市' },
        { cityName: '四平市' },
        { cityName: '辽源市' },
        { cityName: '通化市' },
        { cityName: '白山市' },
        { cityName: '松原市' },
        { cityName: '白城市' },
        { cityName: '延边朝鲜族自治州' },
      ],
    },
    {
      provinceName: '黑龙江省',
      citys: [
        { cityName: '哈尔滨市' },
        { cityName: '齐齐哈尔市' },
        { cityName: '鸡西市' },
        { cityName: '鹤岗市' },
        { cityName: '双鸭山市' },
        { cityName: '大庆市' },
        { cityName: '伊春市' },
        { cityName: '佳木斯市' },
        { cityName: '七台河市' },
        { cityName: '牡丹江市' },
        { cityName: '黑河市' },
        { cityName: '绥化市' },
        { cityName: '大兴安岭地区' },
      ],
    },
    {
      provinceName: '江苏省',
      citys: [
        { cityName: '南京市' },
        { cityName: '无锡市' },
        { cityName: '徐州市' },
        { cityName: '常州市' },
        { cityName: '苏州市' },
        { cityName: '南通市' },
        { cityName: '连云港市' },
        { cityName: '淮安市' },
        { cityName: '盐城市' },
        { cityName: '扬州市' },
        { cityName: '镇江市' },
        { cityName: '泰州市' },
        { cityName: '宿迁市' },
      ],
    },
    {
      provinceName: '浙江省',
      citys: [
        { cityName: '杭州市' },
        { cityName: '宁波市' },
        { cityName: '温州市' },
        { cityName: '嘉兴市' },
        { cityName: '湖州市' },
        { cityName: '绍兴市' },
        { cityName: '金华市' },
        { cityName: '衢州市' },
        { cityName: '舟山市' },
        { cityName: '台州市' },
        { cityName: '丽水市' },
      ],
    },
    {
      provinceName: '安徽省',
      citys: [
        { cityName: '合肥市' },
        { cityName: '芜湖市' },
        { cityName: '蚌埠市' },
        { cityName: '淮南市' },
        { cityName: '马鞍山市' },
        { cityName: '淮北市' },
        { cityName: '铜陵市' },
        { cityName: '安庆市' },
        { cityName: '黄山市' },
        { cityName: '滁州市' },
        { cityName: '阜阳市' },
        { cityName: '宿州市' },
        { cityName: '六安市' },
        { cityName: '亳州市' },
        { cityName: '池州市' },
        { cityName: '宣城市' },
      ],
    },
    {
      provinceName: '福建省',
      citys: [
        { cityName: '福州市' },
        { cityName: '厦门市' },
        { cityName: '莆田市' },
        { cityName: '三明市' },
        { cityName: '泉州市' },
        { cityName: '漳州市' },
        { cityName: '南平市' },
        { cityName: '龙岩市' },
        { cityName: '宁德市' },
      ],
    },
    {
      provinceName: '江西省',
      citys: [
        { cityName: '南昌市' },
        { cityName: '景德镇市' },
        { cityName: '萍乡市' },
        { cityName: '九江市' },
        { cityName: '新余市' },
        { cityName: '鹰潭市' },
        { cityName: '赣州市' },
        { cityName: '吉安市' },
        { cityName: '宜春市' },
        { cityName: '抚州市' },
        { cityName: '上饶市' },
      ],
    },
    {
      provinceName: '山东省',
      citys: [
        { cityName: '济南市' },
        { cityName: '青岛市' },
        { cityName: '淄博市' },
        { cityName: '枣庄市' },
        { cityName: '东营市' },
        { cityName: '烟台市' },
        { cityName: '潍坊市' },
        { cityName: '济宁市' },
        { cityName: '泰安市' },
        { cityName: '威海市' },
        { cityName: '日照市' },
        { cityName: '临沂市' },
        { cityName: '德州市' },
        { cityName: '聊城市' },
        { cityName: '滨州市' },
        { cityName: '菏泽市' },
      ],
    },
    {
      provinceName: '河南省',
      citys: [
        { cityName: '郑州市' },
        { cityName: '开封市' },
        { cityName: '洛阳市' },
        { cityName: '平顶山市' },
        { cityName: '安阳市' },
        { cityName: '鹤壁市' },
        { cityName: '新乡市' },
        { cityName: '焦作市' },
        { cityName: '濮阳市' },
        { cityName: '许昌市' },
        { cityName: '漯河市' },
        { cityName: '三门峡市' },
        { cityName: '南阳市' },
        { cityName: '商丘市' },
        { cityName: '信阳市' },
        { cityName: '周口市' },
        { cityName: '驻马店市' },
        { cityName: '济源市' },
      ],
    },
    {
      provinceName: '湖北省',
      citys: [
        { cityName: '武汉市' },
        { cityName: '黄石市' },
        { cityName: '十堰市' },
        { cityName: '宜昌市' },
        { cityName: '襄阳市' },
        { cityName: '鄂州市' },
        { cityName: '荆门市' },
        { cityName: '孝感市' },
        { cityName: '荆州市' },
        { cityName: '黄冈市' },
        { cityName: '咸宁市' },
        { cityName: '随州市' },
        { cityName: '恩施土家族苗族自治州' },
        { cityName: '仙桃市' },
        { cityName: '潜江市' },
        { cityName: '天门市' },
        { cityName: '神农架林区' },
      ],
    },
    {
      provinceName: '湖南省',
      citys: [
        { cityName: '长沙市' },
        { cityName: '株洲市' },
        { cityName: '湘潭市' },
        { cityName: '衡阳市' },
        { cityName: '邵阳市' },
        { cityName: '岳阳市' },
        { cityName: '常德市' },
        { cityName: '张家界市' },
        { cityName: '益阳市' },
        { cityName: '郴州市' },
        { cityName: '永州市' },
        { cityName: '怀化市' },
        { cityName: '娄底市' },
        { cityName: '湘西土家族苗族自治州' },
      ],
    },
    {
      provinceName: '广西壮族自治区',
      citys: [
        { cityName: '南宁市' },
        { cityName: '柳州市' },
        { cityName: '桂林市' },
        { cityName: '梧州市' },
        { cityName: '北海市' },
        { cityName: '防城港市' },
        { cityName: '钦州市' },
        { cityName: '贵港市' },
        { cityName: '玉林市' },
        { cityName: '百色市' },
        { cityName: '贺州市' },
        { cityName: '河池市' },
        { cityName: '来宾市' },
        { cityName: '崇左市' },
      ],
    },
    {
      provinceName: '海南省',
      citys: [
        { cityName: '海口市' },
        { cityName: '三亚市' },
        { cityName: '三沙市' },
        { cityName: '儋州市' },
        { cityName: '五指山市' },
        { cityName: '琼海市' },
        { cityName: '文昌市' },
        { cityName: '万宁市' },
        { cityName: '东方市' },
        { cityName: '定安县' },
        { cityName: '屯昌县' },
        { cityName: '澄迈县' },
        { cityName: '临高县' },
        { cityName: '白沙黎族自治县' },
        { cityName: '昌江黎族自治县' },
        { cityName: '乐东黎族自治县' },
        { cityName: '陵水黎族自治县' },
        { cityName: '保亭黎族苗族自治县' },
        { cityName: '琼中黎族苗族自治县' },
      ],
    },
    {
      provinceName: '四川省',
      citys: [
        { cityName: '成都市' },
        { cityName: '自贡市' },
        { cityName: '攀枝花市' },
        { cityName: '泸州市' },
        { cityName: '德阳市' },
        { cityName: '绵阳市' },
        { cityName: '广元市' },
        { cityName: '遂宁市' },
        { cityName: '内江市' },
        { cityName: '乐山市' },
        { cityName: '南充市' },
        { cityName: '眉山市' },
        { cityName: '宜宾市' },
        { cityName: '广安市' },
        { cityName: '达州市' },
        { cityName: '雅安市' },
        { cityName: '巴中市' },
        { cityName: '资阳市' },
        { cityName: '阿坝藏族羌族自治州' },
        { cityName: '甘孜藏族自治州' },
        { cityName: '凉山彝族自治州' },
      ],
    },
    {
      provinceName: '贵州省',
      citys: [
        { cityName: '贵阳市' },
        { cityName: '六盘水市' },
        { cityName: '遵义市' },
        { cityName: '安顺市' },
        { cityName: '毕节市' },
        { cityName: '铜仁市' },
        { cityName: '黔西南布依族苗族自治州' },
        { cityName: '黔东南苗族侗族自治州' },
        { cityName: '黔南布依族苗族自治州' },
      ],
    },
    {
      provinceName: '云南省',
      citys: [
        { cityName: '昆明市' },
        { cityName: '曲靖市' },
        { cityName: '玉溪市' },
        { cityName: '保山市' },
        { cityName: '昭通市' },
        { cityName: '丽江市' },
        { cityName: '普洱市' },
        { cityName: '临沧市' },
        { cityName: '楚雄彝族自治州' },
        { cityName: '红河哈尼族彝族自治州' },
        { cityName: '文山壮族苗族自治州' },
        { cityName: '西双版纳傣族自治州' },
        { cityName: '大理白族自治州' },
        { cityName: '德宏傣族景颇族自治州' },
        { cityName: '怒江傈僳族自治州' },
        { cityName: '迪庆藏族自治州' },
      ],
    },
    {
      provinceName: '西藏自治区',
      citys: [
        { cityName: '拉萨市' },
        { cityName: '日喀则市' },
        { cityName: '昌都市' },
        { cityName: '林芝市' },
        { cityName: '山南市' },
        { cityName: '那曲市' },
        { cityName: '阿里地区' },
      ],
    },
    {
      provinceName: '陕西省',
      citys: [
        { cityName: '西安市' },
        { cityName: '铜川市' },
        { cityName: '宝鸡市' },
        { cityName: '咸阳市' },
        { cityName: '渭南市' },
        { cityName: '延安市' },
        { cityName: '汉中市' },
        { cityName: '榆林市' },
        { cityName: '安康市' },
        { cityName: '商洛市' },
      ],
    },
    {
      provinceName: '甘肃省',
      citys: [
        { cityName: '兰州市' },
        { cityName: '嘉峪关市' },
        { cityName: '金昌市' },
        { cityName: '白银市' },
        { cityName: '天水市' },
        { cityName: '武威市' },
        { cityName: '张掖市' },
        { cityName: '平凉市' },
        { cityName: '酒泉市' },
        { cityName: '庆阳市' },
        { cityName: '定西市' },
        { cityName: '陇南市' },
        { cityName: '临夏回族自治州' },
        { cityName: '甘南藏族自治州' },
      ],
    },
    {
      provinceName: '青海省',
      citys: [
        { cityName: '西宁市' },
        { cityName: '海东市' },
        { cityName: '海北藏族自治州' },
        { cityName: '黄南藏族自治州' },
        { cityName: '海南藏族自治州' },
        { cityName: '果洛藏族自治州' },
        { cityName: '玉树藏族自治州' },
        { cityName: '海西蒙古族藏族自治州' },
      ],
    },
    {
      provinceName: '宁夏回族自治区',
      citys: [
        { cityName: '银川市' },
        { cityName: '石嘴山市' },
        { cityName: '吴忠市' },
        { cityName: '固原市' },
        { cityName: '中卫市' },
      ],
    },
    {
      provinceName: '新疆维吾尔自治区',
      citys: [
        { cityName: '乌鲁木齐市' },
        { cityName: '克拉玛依市' },
        { cityName: '吐鲁番市' },
        { cityName: '哈密市' },
        { cityName: '昌吉回族自治州' },
        { cityName: '博尔塔拉蒙古自治州' },
        { cityName: '巴音郭楞蒙古自治州' },
        { cityName: '阿克苏地区' },
        { cityName: '克孜勒苏柯尔克孜自治州' },
        { cityName: '喀什地区' },
        { cityName: '和田地区' },
        { cityName: '伊犁哈萨克自治州' },
        { cityName: '塔城地区' },
        { cityName: '阿勒泰地区' },
        { cityName: '石河子市' },
        { cityName: '阿拉尔市' },
        { cityName: '图木舒克市' },
        { cityName: '五家渠市' },
        { cityName: '北屯市' },
        { cityName: '铁门关市' },
        { cityName: '双河市' },
        { cityName: '可克达拉市' },
        { cityName: '昆玉市' },
        { cityName: '胡杨河市' },
        { cityName: '新星市' },
      ],
    },
    {
      citys: [
        { cityName: '台北市' },
        { cityName: '新北市' },
        { cityName: '桃园市' },
        { cityName: '台中市' },
        { cityName: '台南市' },
        { cityName: '高雄市' },
        { cityName: '基隆市' },
        { cityName: '新竹市' },
        { cityName: '嘉义市' },
      ],
      provinceName: '台湾省',
    },
  ];
}
